//
// modules/text-samples.js
//   Text samples for annotation.
//
/*global define */
define({
	samples: [
		'In Duchenne muscular dystrophy (DMD), the infiltration of skeletal muscle by immune cells aggravates disease, yet the precise mechanisms behind these inflammatory responses remain poorly understood. Chemotactic cytokines, or chemokines, are considered essential recruiters of inflammatory cells to the tissues.\nWe assayed chemokine and chemokine receptor expression in DMD muscle biopsies (n = 9, average age 7 years) using immunohistochemistry, immunofluorescence, and in situ hybridization.\nCXCL1, CXCL2, CXCL3, CXCL8, and CXCL11, absent from normal muscle fibers, were induced in DMD myofibers. CXCL11, CXCL12, and the ligand-receptor couple CCL2-CCR2 were upregulated on the blood vessel endothelium of DMD patients. CD68(+) macrophages expressed high levels of CXCL8, CCL2, and CCL5.\nOur data suggest a possible beneficial role for CXCR1/2/4 ligands in managing muscle fiber damage control and tissue regeneration. Upregulation of endothelial chemokine receptors and CXCL8, CCL2, and CCL5 expression by cytotoxic macrophages may regulate myofiber necrosis.',
		'There is conflicting literature regarding the association of the BRAF V600E mutation and aggressive clinicopathological features of papillary thyroid cancer (PTC). Nevertheless, some propose that BRAF status be incorporated into the management of patients with PTC, specifically recommendations regarding lymph node dissection. We therefore performed a meta-analysis to examine the relationship between BRAF and clinicopathological features of PTC.\nA literature search was performed within PubMed and EMBASE databases using the following Medical Subject Headings (MeSH) and keywords: "braf," "mutation," "thyroid," "neoplasm(s)," "tumor," "cancer," and "carcinoma." Individual study-specific odds ratios and confidence intervals were calculated, as were Mantel-Haenszel pooled odds ratios for the combined studies.\nThirty-two studies including 6372 patients were reviewed. BRAF mutation was associated with lymph node metastases (LNM), advanced stage, extrathyroidal extension, tumor size, male gender, multifocality, absence of capsule, classic PTC, and tall-cell variant PTC. There was no association with age or vascular invasion. Only two studies were prospective; nine included consecutive patients, whereas one included randomly selected patients; and only two included patients who had undergone routine central lymph node dissection and were thus evaluable for the presence of LNM.\nMeta-analysis found that BRAF mutation is associated with LNM, stage, extrathyroidal extension, tumor size, male gender, multifocality, absence of capsule, classic PTC, and tall-cell variant PTC in PTC. However, almost all studies were retrospective and only two of 32 included patients who had undergone routine central lymph node dissection, emphasizing the need for well-designed studies to appropriately examine this association before making important clinical decisions.',
		'Histidinemia is an inborn error of metabolism of amino acids caused by deficiency of histidase activity in liver and skin with consequent accumulation of histidine in plasma and tissues. Histidinemia is an autosomal recessive trait usually considered harmless to patients and their offspring, but some patients and children born from histidinemic mothers have mild neurologic alterations. Considering that histidinemia is one of the most frequently identified metabolic conditions, in the present study we investigated the effect of L-histidine load to female rats during pregnancy and lactation on some parameters of phosphoryltransfer network in cerebral cortex and hippocampus of the offspring. Pyruvate kinase, cytosolic and mitochondrial creatine kinase activities decreased in cerebral cortex and in hippocampus of rats at 21 days of age and this pattern remained in the cerebral cortex and in hippocampus at 60 days of age. Moreover, adenylate kinase activity was reduced in the cerebral cortex and in hippocampus of the offspring at 21 days of age, whereas the activity was increased in the two tissues at 60 days of age. These results suggest that administration of L-histidine to female rats in the course of pregnancy and lactation could impair energy homeostasis in the cerebral cortex and hippocampus of the offspring. Considering that histidinemia is usually a benign condition and little attention has been given to maternal histidinemia, it seems important to perform more studies in the children born from histidinemic mothers.',
		'The present study investigated the anti-ageing activity of sesamin and its effect on gene expression of superoxide dismutase (SOD), catalase (CAT), methuselah (Mth) and Rpn11 in Drosophila melanogaster. Results demonstrated that 0.2 % sesamin in diet prolonged the mean lifespan of OR wild fruit flies by 12 %, accompanied by up-regulation of SOD1, SOD2, CAT and Rpn11. Sesamin at 0.2 % in diet also attenuated paraquat-induced neurodegeneration with up-regulation of SOD1, SOD2 and Rpn11 in OR wild fruit flies. Supplementation of 0.2 % sesamin in diet increased the survival time of OR wild type flies and Alzheimer flies Aβ42 33769 when they were challenged with paraquat. Furthermore, sesamin-induced increase in the activity and expression of antioxidant enzymes also suggests that the longevity promoting activity of sesamin are possibly due to its action as a hormetin by inducing oxidative stress response-mediated hormesis. It was concluded that sesamin extended the mean lifespan and alleviated the neurodegeneration in Drosophila melanogaster at least mediated by its interaction with genes SOD1, SOD2, CAT, and Rpn11, but not with gene Mth.',
		'In Alzheimer disease, neuronal degeneration and the presence of neurofibrillary tangles correlate with the severity of cognitive decline. Neurofibrillary tangles contain the antigenic profile of many cell cycle markers, reflecting a re-entry into the cell cycle by affected neurons. However, while such a cell cycle re-entry phenotype is an early and consistent feature of Alzheimer disease, the mechanisms responsible for neuronal cell cycle are unclear. In this regard, given that a dysregulated cell cycle is a characteristic of cancer, we speculated that alterations in oncogenic proteins may play a role in neurodegeneration. To this end, in this study, we examined brain tissue from cases of Alzheimer disease for the presence of BRCA1, a known regulator of cell cycle, and found intense and specific localization of BRCA1 to neurofibrillary tangles, a hallmark lesion of the disease. Analysis of clinically normal aged brain tissue revealed systematically less BRCA1, and surprisingly in many cases with apparent phosphorylated tau-positive neurofibrillary tangles, BRCA1 was absent, yet BRCA1 was present in all cases of Alzheimer disease. These findings not only further define the cell cycle reentry phenotype in Alzheimer disease but also indicate that the neurofibrillary tangles which define Alzheimer disease may have a different genesis from the neurofibrillary tangles of normal aging.'
	],

	pmids: [
		{pmid: 23225384, title: 'Upregulation of chemokines and their receptors in Duchenne muscular dystrophy: potential for attenuation of myofiber necrosis.'},
		{pmid: 23055546, title: 'BRAF V600E mutation and its association with clinicopathological features of papillary thyroid cancer: a meta-analysis.'},
		{pmid: 22638695, title: 'Effect of histidine administration to female rats during pregnancy and lactation on enzymes activity of phosphoryltransfer network in cerebral cortex and hippocampus of the offspring.', isLast: true}
		// {pmid: 23291977, title: 'Sesamin extends the mean lifespan of fruit flies.'},
		// {pmid: 17505559, title: 'BRCA1 may modulate neuronal cell cycle re-entry in Alzheimer disease.', isLast: true}
	]
});